### ISSUE TITLE
fungsi logout implicit-client

### ISSUE THREAD

**Issue by adriyudo** [endymuhardin/belajar-springoauth2#2]
Sebelumnya terimakasih atas tutorialnya mas endy, namun fungsi logout pada sampel implicit-client yang menggunakan angular tidak jalan sepertinya karena auth server membutuhkan post dan csrf. udah coba dirubah pake jsp tp variable csrfnya belum terisi jg dan cb pake XSRF-TOKEN bawaan angular dan pasang statement diauth-server-> and().csrf().csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse());  tp masih belum bisa jg -_-  mohon pencerahannya mas endy, terimakasih

**Comment by endymuhardin** [comment]
Logout di OAuth memang tidak didefinisikan dengan jelas. Soalnya ada banyak aplikasi yang terlibat. Misalnya kita logout di aplikasi client, apakah artinya logout juga di resource server, atau di authserver?
Misalnya, kita pakai aplikasi yang login with google. Pas kita logout, apakah ikut logout juga dari Google?

Nah ini gak diatur di spec OAuth, jadi ya implement masing2 aja.

Masalah berikutnya, kalau kita pakai JWT, resource server gak perlu cek ke authserver tentang validitas token karena dia bisa verifikasi sendiri pakai public key. Karena resource server gak nanya ke authserver, jadi kita gak bisa memaksa tokennya invalid/expire. Paling nunggu dia expire sendiri.
