### ISSUE TITLE
auth server dari datasource

### ISSUE THREAD

**Issue by Widiyanto** [endymuhardin/belajar-springoauth2#4]
Terimakasih mas sebelumnya, sangat bermanfaat sekali.
saya coba ubah auth-server dikoneksikan ke database dan berjalan lancar, tapi ada kendala token yang didapat dari auth-server itu selalu tidak kebaca ketika memanggil request ke resource-server.
apa yang saya harus ubah di resource-servernya ya?

Terimakasih

**Comment by endymuhardin** [comment]
Tidak kebaca maksudnya gimana?
Coba upload ke github projectnya supaya bisa dicek konfigurasinya

**Comment by Widiyanto** [comment]
Udah Pak endy solved. ternyata salahnya hanya di prefix ROLE_, yang Pak endy pakai di AUTH SERVER untuk cek token adalah `oauthServer.checkTokenAccess("hasRole('CLIENT')");`   itu sudah benar karena dia membaca `ClientDetailsServiceConfigurer` yang salah satu isinya `.withClient("jsclient")
                        .secret("jspasswd")
                        .authorizedGrantTypes("implicit")
                        .scopes("read", "write")
                        .resourceIds(RESOURCE_ID)
                        .authorities("CLIENT")
                        .redirectUris("http://localhost:20000/implicit-client/")
                        .accessTokenValiditySeconds(60 * 60 * 24) 
                        .autoApprove(true)
                    ;` dan jika itu dilakukan di inMemory `hasRole('CLIENT')` tidak memerlukan prefix ROLE_, sedangkan kasus saya ambil dari database, ternyata AUTHORITIES column pada table OAUTH_CLIENT_DETAILS di schema OAUTH2 saya harus isi dengan menggunakan ROLE_CLIENT agar terbaca di `oauthServer.checkTokenAccess("hasRole('CLIENT')");` sebelumnya saya hanya isi CLIENT.

Terimakasih banyak untuk ilmunya.

Salam
Widiyanto

**Comment by endymuhardin** [comment]
Bikin issue juga ya di Githubnya Spring? 
Jangan lupa diclose tuh. Tulis juga solusinya.

Kalau mau tanpa `ROLE_`, ngeceknya pakai `hasAuthority('CLIENT')`, jangan pakai `hasRole`

**Comment by Widiyanto** [comment]
Iya Pak sudah saya close issuenya.

Ya bener Pak hasRole hasAuthority yang membedakan hanya prefix ROLE_
