### ISSUE TITLE
Penggunaan state parameter pada Flow Grant Type Implicit

### ISSUE THREAD

**Issue by Widiyanto** [endymuhardin/belajar-springoauth2#6]
Izin bertanya Pak Endy, untuk penggunaan state parameter pada Flow Grant Type Implicit untuk apa?
karena saya coba implementasikan menggunakan state dan tanpa menggunakan state parameter dan direct url ke http://localhost:10001/api/state/verify itu sama-sama menghasilkan token yang bisa digunakan untuk akses data.

**Comment by endymuhardin** [comment]
Coba baca ini https://auth0.com/docs/protocols/oauth2/oauth-state

**Comment by Widiyanto** [comment]
- `auth-server`  : authorization server, memegang username dan password dan bertugas melakukan otentikasi.
- `resource-server`  : penyedia layanan (API) yang ingin diakses dari aplikasi. `Resource server` tidak melakukan pemeriksaan username/password, dia mendelegasikan otentikasi ke `auth-server`.
- `client-application` : aplikasi yang dihadapi user. Aplikasi ini menggunakan layanan dari `resource-server`.
- `resource-owner` : pemilik data dalam `resource-server.` Disebut juga dengan istilah `user `pada `client-application`.

berarti yang membuat code/random string `state` itu dari `client-application`?

**Comment by endymuhardin** [comment]
Iya benar, state digenerate oleh client-application. Auth server cuma
balikin apa yang dia terima aja

Endy Muhardin
http://software.endy.muhardin.com

**Comment by Widiyanto** [comment]
Baik terima kasih atas jawabannya Pak. sangat membuka pandangan saya mengenai Grant Type Implicit

**Comment by Widiyanto** [comment]
Izin bertanya kembali Pak Endy, untuk mengurangi redudansi akses code di `controller`. 

Anggap saja saya punya aplikasi `resource-server`  bernama `CUACA`.

selain `resource-server` adalah penyedia layanan API untuk aplikasi lain, saya ingin gabung juga aplikasi berupa form page jsp di `resource-server`. 
- Apakah form jsp pada `resource-server` yang ingin saya buat tersebut perlakuanya sama seperti Aplikasi lain yang ingin akses `resource server` menggunakan grant type dari OAUTH? 
- Sebaiknya aplikasi form page jsp saya pisahkan projeknya dari `resource-server` dan punya `controller` sendiri dan akses menggunakan menggunakan grant type dari OAUTH ke  `resource-server? 
- Apakahkah di gabung di satu aplikasi terus buat pisah mapping urlnya? dan configurasi di `NonOauthResources extends WebSecurityConfigurerAdapter` ?

`@Configuration
public class Oauth2ResourceServer {

    private static final String RESOURCE_ID = "belajar";
    
    @Autowired
    private static CustomAccessTokenConverter customAccessTokenConverter;

    @Configuration @Order(10)
    protected static class NonOauthResources extends WebSecurityConfigurerAdapter {

        @Override
        protected void configure(HttpSecurity http) throws Exception {
            http
	            //.formLogin().loginPage("/welcome").permitAll().and()
	            .authorizeRequests()
	            .antMatchers("/api/halo").permitAll()
	            .antMatchers("/api/state/**").permitAll()
	            .antMatchers("/**").permitAll()
	            .antMatchers("/students/**").permitAll()
	            .and().anonymous();
        }
    }

    @Configuration
    @EnableResourceServer
    protected static class ResourceServerConfiguration extends
            ResourceServerConfigurerAdapter {

        @Override
        public void configure(ResourceServerSecurityConfigurer resources) {
            /*RemoteTokenServices tokenService = new RemoteTokenServices();
            tokenService.setClientId("jsclient");
            tokenService.setClientSecret("jspasswd");
            tokenService.setCheckTokenEndpointUrl("http://localhost:100/oauth/check_token");*/
            
            resources
                    .resourceId(RESOURCE_ID)
                    //.tokenServices(tokenService);
                    .tokenServices(tokenServices());
        }

        @Override
        public void configure(HttpSecurity http) throws Exception {
        	//http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.IF_REQUIRED);
            http.authorizeRequests()
                    .antMatchers("/api/staff").hasAuthority("STAFF")
                    .antMatchers("/api/client").access("#oauth2.hasScope('trust')")
                    .antMatchers("/api/admin").authenticated()
                    .antMatchers("/api/hai").authenticated()
                    .antMatchers("/api/userLogin").authenticated();
        }
        
        @Bean
        public TokenStore tokenStore() {
            return new CustomJwtTokenStore(accessTokenConverter());
        }

        @Bean
        public JwtAccessTokenConverter accessTokenConverter() {
            final JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
            converter.setSigningKey("MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArHEPCdq4VoLeN6PgrZi6"+
							"OeuWlfodxM3jLKbcypNOFgtjK9ZkW+yJSrO+05Mp83tZuBNWcwaLSzt3BLJknhEp"+
							"lh00hQ1ksFaTd+3tZo9peD3WQivnp0L6+sjwxw0Ngm+v7DhjoMQClaWRGrGeiSEk"+
							"XXWcK41Aq8Kq6h8P6lrT76HGE9QffNcGCjNuRyyCIhpygc9tWKEp/Wh2JQWbfqDl"+
							"ZylorZXaLNYPZ8f4WE5NQ3Gpjh3/78tB06BrWhOTT+t0IojDRcUwAoGdKIMUO77M"+
							"0OdgnEWYpFI24XuC3beXGXlE0qGuagIWQNaEDhzJ9uOkZlqeKh0ok7d4SbYG1u3r"+
							"2QIDAQAB"); //symetrik
            //converter.setAccessTokenConverter(customAccessTokenConverter);
            return converter;
        }

        @Bean
        @Primary
        public DefaultTokenServices tokenServices() {
            final DefaultTokenServices defaultTokenServices = new DefaultTokenServices();
            defaultTokenServices.setTokenStore(tokenStore());
            return defaultTokenServices;
        }
    }

}
`

**Comment by endymuhardin** [comment]
Coba nonton ini
https://www.youtube.com/watch?v=jSbMvRxQDpc

Endy Muhardin
http://software.endy.muhardin.com

**Comment by Widiyanto** [comment]
Baik Pak terimkasih, btw sudah saya subsribe juga youtubenya. hhhe

**Comment by Widiyanto** [comment]
Terimkasih Pak, saya akan coba explore.
Di benak saya muncul pertanyaan baru Pak untuk manajemen user untuk otentikasi di `auth-server.`
saya akan memisahkan antara `auth-server` dan `resource-server`.

anggapan saya punya satu aplikasi `auth-server`. `auth-server` di sini saya gunakan otentikasi untuk banyak aplikasi `resource-server`.

apakah user di `resource-server`  saya harus daftarkan juga di `auth-server`?

**Comment by endymuhardin** [comment]
Manajemen user itu ada dua:
- authentication : memeriksa identitas user (biasanya cek username dan
password)
- authorization : memeriksa ijin akses user (user A bisa akses fitur apa
aja)

Yang authentication itu di authserver.
Authorization bebas aja mau tersentralisasi di authserver atau mau dihandle
masing-masing resource server.


Endy Muhardin
http://software.endy.muhardin.com

**Comment by Widiyanto** [comment]
Terima kasih Pak, sekarang sudah Paham, dan saya sudah berhasil mengimplementasikan Aplikasi Jaman Now. Hhhhee
Aplikasi berbasis form, juga bisa menyediakan layanan API untuk Aplikasi lain dengan Aman.
